Updating the build script and init script to work on centos6

diff --git a/centos/6/puppyforge.init b/centos/6/puppyforge.init
--- a/centos/6/puppyforge.init
+++ b/centos/6/puppyforge.init
@@ -1,3 +1,4 @@
+#!/bin/bash
 ### BEGIN INIT INFO
 # Provides:          puppyforge
 # Required-Start:    networking
@@ -9,78 +10,96 @@
 #                    can serve files from the filesystem with the v3 API.
 ### END INIT INFO
 
+
+# Defined here for distributions that don't define
+# log_end_msg
+log_end_msg () {
+  retval=$1
+  if [ ! $retval -eq 0 ]; then
+    echo " failed!"
+  fi
+  return $retval
+}
+
 # Using the lsb functions to perform the operations.
-. /lib/lsb/init-functions
+. /etc/init.d/functions
 # Process name ( For display )
 NAME=puppyforge
 # Daemon name, where is the actual executable
 DAEMON=/usr/local/bin/puppyforge
 # pid file for the daemon
 PIDFILE=/var/run/puppyforge.pid
+LOGFILE=/var/log/puppyforge.log
+LANG="C"
 
 # If the daemon is not there, then exit.
 test -x $DAEMON || exit 5
 
+
+start() {
+    # Checked the PID file exists and check the actual status of process
+    if [ -e $PIDFILE ]; then
+        status_of_proc -p $PIDFILE $DAEMON "$NAME process" && status="0" || status="$?"
+        # If the status is SUCCESS then don't need to start again.
+        if [ $status = "0" ]; then
+            exit # Exit
+        fi
+    fi
+    # Start the daemon.
+    echo -n "Starting $NAME: "
+    # Start the daemon with the help of daemon
+    daemon --pidfile $PIDFILE "nohup $DAEMON >$LOGFILE 2>&1 &"
+    RETVAL=$?
+    [ $RETVAL = 0 ] && pidofproc $DAEMON > $PIDFILE
+    echo ""
+}
+
+stop() {
+    # Stop the daemon.
+    if [ -e $PIDFILE ]; then
+        checkpid $(cat $PIDFILE) && status="0" || status="$?"
+        if [ "$status" = 0 ]; then
+            echo -n "Stopping $NAME: "
+            killproc -p $PIDFILE $DAEMON
+            echo ""
+        fi
+    else
+        echo "$NAME is not running"
+    fi
+}
+
+status() {
+    if [ -e $PIDFILE ]; then
+        checkpid $(cat $PIDFILE)
+        local retcode=$?
+        if [ $retcode == 0 ]; then
+            echo "$NAME (pid $(cat $PIDFILE)) is running..." && exit 0
+        else
+            exit $retcode
+        fi
+    else
+       echo "$NAME is not running"
+    fi
+}
+
 case $1 in
- start)
-  # Checked the PID file exists and check the actual status of process
-  if [ -e $PIDFILE ]; then
-   status_of_proc -p $PIDFILE $DAEMON "$NAME process" && status="0" || status="$?"
-   # If the status is SUCCESS then don't need to start again.
-   if [ $status = "0" ]; then
-    exit # Exit
-   fi
-  fi
-  # Start the daemon.
-  log_daemon_msg "Starting the process" "$NAME"
-  # Start the daemon with the help of start-stop-daemon
-  # Log the message appropriately
-  if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON ; then
-   log_end_msg 0
-  else
-   log_end_msg 1
-  fi
-  ;;
- stop)
-  # Stop the daemon.
-  if [ -e $PIDFILE ]; then
-   status_of_proc -p $PIDFILE $DAEMON "Stoppping the $NAME process" && status="0" || status="$?"
-   if [ "$status" = 0 ]; then
-    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
-    /bin/rm -rf $PIDFILE
-   fi
-  else
-   log_daemon_msg "$NAME process is not running"
-   log_end_msg 0
-  fi
-  ;;
- restart)
-  # Restart the daemon.
-  $0 stop && sleep 2 && $0 start
-  ;;
- status)
-  # Check the status of the process.
-  if [ -e $PIDFILE ]; then
-   status_of_proc -p $PIDFILE $DAEMON "$NAME process" && exit 0 || exit $?
-  else
-   log_daemon_msg "$NAME Process is not running"
-   log_end_msg 0
-  fi
-  ;;
- reload)
-  # Reload the process. Basically sending some signal to a daemon to reload
-  # it configurations.
-  if [ -e $PIDFILE ]; then
-   start-stop-daemon --stop --signal USR1 --quiet --pidfile $PIDFILE --name $NAME
-   log_success_msg "$NAME process reloaded successfully"
-  else
-   log_failure_msg "$PIDFILE does not exists"
-  fi
-  ;;
- *)
-  # For invalid arguments, print the usage message.
-  echo "Usage: $0 {start|stop|restart|reload|status}"
-  exit 2
-  ;;
+    start)
+        start
+        ;;
+    stop)
+        stop
+        ;;
+    restart)
+        stop
+        start
+        ;;
+    status)
+        status
+        RETVAL=$?
+        ;;
+    *)
+        echo "Usage : $NAME {start|stop|restart|status}"
+        RETVAL=2
 esac
 
+exit $RETVAL
